// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awbqsxvxuqwzwmufpyvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3YnFzeHZ4dXF3endtdWZweXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1Mjc1NDMsImV4cCI6MjA1NTEwMzU0M30.tkxwuK2Puu__2rUJtzuGI1QMc0Ux49_qqWxMS39uU7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);